// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Back: typeof import('./components/Back.vue')['default']
    Background: typeof import('./components/Background.vue')['default']
    CodeGroup: typeof import('./components/CodeGroup.vue')['default']
    CodeGroupItem: typeof import('./components/CodeGroupItem.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Giscus: typeof import('./components/Giscus.vue')['default']
    ListGames: typeof import('./components/ListGames.vue')['default']
    ListLifeStyle: typeof import('./components/ListLifeStyle.vue')['default']
    ListLinks: typeof import('./components/ListLinks.vue')['default']
    ListNotes: typeof import('./components/ListNotes.vue')['default']
    ListPosts: typeof import('./components/ListPosts.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    PostPager: typeof import('./components/PostPager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepFlow: typeof import('./components/StepFlow.vue')['default']
    StepFlowItem: typeof import('./components/StepFlowItem.vue')['default']
    SubNav: typeof import('./components/SubNav.vue')['default']
    VitesstQB: typeof import('./components/icons/VitesstQB.vue')['default']
  }
}
